config/routes.rb
Rails.application.routes.draw do
  root 'landing#index'
  resources :plates do
      resources :ingredients , except: [:index]
      member do
        post 'upvote'
  end
end

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :plate
  validates :content, presence: true
end

app/models/plate.rb
class Plate < ActiveRecord::Base

  has_many :ingredients, dependent: :destroy
  has_many :votes, dependent: :destroy
  validates :title, :description, :producer, presence: true
  validates :description, length: { minimum: 10 }
  validates :title, uniqueness: { scope: :producer, message: 'should happen once per producer' }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable, :confirmable, :rememberable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :plate
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_sign_up_params, if: :devise_controller?

  protected
    def configure_sign_up_params
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name, :email, :password])
    end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_plate
  before_action :set_ingredient, only: [:edit, :update, :destroy]

  def new
    @ingredient = @plate.ingredients.new
  end

  def create
    @ingredient = @plate.ingredients.new(ingredient_params)
    if @ingredient.save
      redirect_to @plate, notice: 'Ingredient was successfully created.'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @ingredient.update(ingredient_params)
      redirect_to @plate, notice: 'Ingredient was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @ingredient.destroy
    redirect_to @plate, notice: 'Ingredient was successfully destroyed.'
  end

  private

  def set_plate
    @plate = Plate.find(params[:plate_id])
  end

  def set_ingredient
    @ingredient = @plate.ingredients.find(params[:id])
  end

  def ingredient_params
    params.require(:ingredient).permit(:id, :content, :plate_id)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/plates_controller.rb
class PlatesController < ApplicationController
  before_action :set_plate, only: [:show, :edit, :update, :destroy]

  def index
    @plates = Plate.all
  end

  def new
    @plate = Plate.new
  end

  def create
    @plate = Plate.new(plate_params)
    if @plate.save
      redirect_to plates_path, notice: 'Plate was successfully created.'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @plate.update(plate_params)
      redirect_to plates_path, notice: 'Plate was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @plate.destroy
    redirect_to plates_path, notice: 'Plate was successfully destroyed.'
  end

  def show
  end

  def upvote
    @plate = Plate.find(params[:id])
    @plate.votes.create
    redirect_to(plates_path)
  end

  private

  def plate_params
    params.require(:plate).permit(:id, :title, :description, :producer)
  end

  def set_plate
    @plate = Plate.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/plates_helper.rb
module PlatesHelper
end

app/views/ingredients/_form.html.erb
<%= form_for [@plate, @ingredient ] do |f| %>
  <% if @ingredient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ingredient.errors.count, "error") %> prohibited this tower from being saved:</h2>

      <ul>
      <% @ingredient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div >
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>

  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/ingredients/_ingredients.html.erb
<h1>Listing Ingredient</h1>

<table>
  <thead>
    <tr>
      <th>content</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% ingredients.each do |ingredient| %>
      <tr>
        <td><%= ingredient.content %></td>
        <td><%= link_to 'Edit', edit_plate_ingredient_path(@plate, ingredient) %></td>
        <td><%= link_to 'Destroy', [@plate, ingredient], method: :delete, data: { confirm: 'Are you sure?' } %></td>


      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Ingredient', new_plate_ingredient_path(@plate) %>

app/views/ingredients/edit.html.erb
<h1>Plate: <%= @plate.title%></h1>
<h2>Edit Ingredients</h2>
<%= render 'form'%>

app/views/ingredients/new.html.erb
<h1>Plate: <%= @plate.title%></h1>
<h2>New Ingredients</h2>
<%= render 'form'%>

app/views/landing/index.html.erb
<h1> foodie is comming!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Foodie</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p><%=flash[:notice]%><p>

<% if user_signed_in? %>
  <li>
    <%= link_to 'Plates', plates_path %>
  </li>
  <li>
    <%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %>
  </li>
<% else %>
  <li>
    <%= link_to 'Login in', new_user_session_path %>
  </li>
  <li>
    <%= link_to 'Sign up', new_user_registration_path %>
  </li>
<% end %>
<%= yield %>

</body>
</html>

app/views/plates/_form.html.erb
<%= form_for(@plate) do |f| %>
  <% if @plate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@plate.errors.count, "error") %> prohibited this plate from being saved:</h2>

      <ul>
      <% @plate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :title , "Title"%><br>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div>
    <%= f.label :producer %><br>
    <%= f.text_field :producer %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/plates/edit.html.erb
<h1>Edit Plate</h1>
<%= render 'form'%>

app/views/plates/index.html.erb
<h1>Listing Plates</h1>

<table>
  <thead>
    <tr>
      <th>title</th>
      <th>description</th>
      <th>producer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plates.each do |plate| %>
      <tr>
        <td><%= plate.title %></td>
        <td><%= plate.description.truncate(30) %></td>
        <td><%= plate.producer %></td>
        <td><%= link_to 'Show Ingredients', plate %></td>
        <td><%= link_to 'Edit', edit_plate_path(plate) %></td>
        <td><%= link_to 'Destroy', plate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= pluralize(plate.votes.count, "vote") %></td>
        <td><%= button_to '+1', upvote_plate_path(plate), method: :post %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plate', new_plate_path %>

app/views/plates/new.html.erb
<h1>New Plate</h1>
<%= render 'form' %>

app/views/plates/show.html.erb
<p>
<strong> Plate:  </strong>
  <%= @plate.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @plate.description %>
</p>

<p>
  <strong>Producer:</strong>
  <%= @plate.producer %>
</p>

<%= render partial: 'ingredients/ingredients', locals: { ingredients: @plate.ingredients.order(created_at: :asc)} %>